// prisma/seed-hospitals.ts
// Seed de hospitales del catalogo CLUES para CDMX con especialidades

import { PrismaClient, InstitutionType, AttentionLevel } from '@prisma/client';

const prisma = new PrismaClient();

// Mapeo de condiciones médicas a especialidades relevantes
export const conditionToSpecialties: Record<string, string[]> = {
  'Diabetes': ['Endocrinologia', 'Medicina Interna', 'Nefrologia', 'Oftalmologia'],
  'Diabetes Mellitus': ['Endocrinologia', 'Medicina Interna', 'Nefrologia'],
  'Hipertension': ['Cardiologia', 'Medicina Interna', 'Nefrologia'],
  'Hipertension Arterial': ['Cardiologia', 'Medicina Interna'],
  'Cardiopatia': ['Cardiologia', 'Cirugia Cardiovascular'],
  'Infarto': ['Cardiologia', 'Urgencias', 'UCI'],
  'Asma': ['Neumologia', 'Alergologia', 'Medicina Interna'],
  'EPOC': ['Neumologia', 'Medicina Interna'],
  'Cancer': ['Oncologia', 'Cirugia Oncologica', 'Radioterapia'],
  'Traumatismo': ['Traumatologia', 'Ortopedia', 'Urgencias'],
  'Fractura': ['Traumatologia', 'Ortopedia'],
  'Embarazo': ['Ginecologia', 'Obstetricia', 'Neonatologia'],
  'Pediatrico': ['Pediatria', 'Neonatologia'],
  'Renal': ['Nefrologia', 'Urologia'],
  'Neurologico': ['Neurologia', 'Neurocirugia'],
  'ACV': ['Neurologia', 'Urgencias', 'UCI'],
  'Psiquiatrico': ['Psiquiatria', 'Salud Mental'],
};

// Hospitales reales de CDMX con coordenadas y especialidades
const hospitalesCDMX = [
  {
    cluesCode: 'DFSSA000015',
    name: 'Hospital General de Mexico Dr. Eduardo Liceaga',
    type: InstitutionType.HOSPITAL_PUBLIC,
    attentionLevel: AttentionLevel.THIRD,
    address: 'Dr. Balmis 148, Doctores',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    zipCode: '06720',
    latitude: 19.4117,
    longitude: -99.1525,
    phone: '55 2789 2000',
    emergencyPhone: '55 2789 2000 ext. 1101',
    specialties: ['Urgencias', 'Medicina Interna', 'Cardiologia', 'Neurologia', 'Traumatologia', 'Oncologia', 'Nefrologia', 'Cirugia General', 'UCI'],
    hasEmergency: true,
    has24Hours: true,
    hasICU: true,
    hasTrauma: true,
  },
  {
    cluesCode: 'DFSSA000165',
    name: 'Hospital General Dr. Manuel Gea Gonzalez',
    type: InstitutionType.HOSPITAL_PUBLIC,
    attentionLevel: AttentionLevel.THIRD,
    address: 'Calz. de Tlalpan 4800, Tlalpan',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    zipCode: '14080',
    latitude: 19.2985,
    longitude: -99.1494,
    phone: '55 4000 3000',
    emergencyPhone: '55 4000 3000',
    specialties: ['Urgencias', 'Medicina Interna', 'Cardiologia', 'Cirugia Plastica', 'Dermatologia', 'Oftalmologia', 'UCI'],
    hasEmergency: true,
    has24Hours: true,
    hasICU: true,
    hasTrauma: false,
  },
  {
    cluesCode: 'DFSSA000081',
    name: 'Hospital Juarez de Mexico',
    type: InstitutionType.HOSPITAL_PUBLIC,
    attentionLevel: AttentionLevel.THIRD,
    address: 'Av. Instituto Politecnico Nacional 5160',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    zipCode: '07760',
    latitude: 19.4833,
    longitude: -99.1345,
    phone: '55 5747 7560',
    emergencyPhone: '55 5747 7560',
    specialties: ['Urgencias', 'Medicina Interna', 'Ginecologia', 'Obstetricia', 'Pediatria', 'Cirugia General', 'Traumatologia', 'UCI'],
    hasEmergency: true,
    has24Hours: true,
    hasICU: true,
    hasTrauma: true,
  },
  {
    cluesCode: 'DFIMSS00125',
    name: 'Hospital General de Zona No. 32 Villa Coapa',
    type: InstitutionType.IMSS,
    attentionLevel: AttentionLevel.SECOND,
    address: 'Calz. del Hueso 800, Coapa',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    zipCode: '14310',
    latitude: 19.3017,
    longitude: -99.1305,
    phone: '55 5684 2655',
    emergencyPhone: '55 5684 2655',
    specialties: ['Urgencias', 'Medicina Interna', 'Ginecologia', 'Pediatria', 'Cirugia General'],
    hasEmergency: true,
    has24Hours: true,
    hasICU: false,
    hasTrauma: false,
  },
  {
    cluesCode: 'DFIMSS00137',
    name: 'Hospital General de Zona No. 27 Tlatelolco',
    type: InstitutionType.IMSS,
    attentionLevel: AttentionLevel.SECOND,
    address: 'Av. Insurgentes Norte 423, Nonoalco-Tlatelolco',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    zipCode: '06900',
    latitude: 19.4511,
    longitude: -99.1408,
    phone: '55 5583 5733',
    emergencyPhone: '55 5583 5733',
    specialties: ['Urgencias', 'Medicina Interna', 'Ginecologia', 'Pediatria', 'Traumatologia'],
    hasEmergency: true,
    has24Hours: true,
    hasICU: false,
    hasTrauma: true,
  },
  {
    cluesCode: 'DFIST00011',
    name: 'Hospital Regional 1o de Octubre ISSSTE',
    type: InstitutionType.ISSSTE,
    attentionLevel: AttentionLevel.THIRD,
    address: 'Av. Instituto Politecnico Nacional 1669',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    zipCode: '07760',
    latitude: 19.4822,
    longitude: -99.1276,
    phone: '55 5586 7499',
    emergencyPhone: '55 5586 7499',
    specialties: ['Urgencias', 'Cardiologia', 'Neurologia', 'Oncologia', 'Nefrologia', 'Endocrinologia', 'UCI'],
    hasEmergency: true,
    has24Hours: true,
    hasICU: true,
    hasTrauma: false,
  },
  {
    cluesCode: 'DFPRI00234',
    name: 'Hospital Angeles Pedregal',
    type: InstitutionType.HOSPITAL_PRIVATE,
    attentionLevel: AttentionLevel.THIRD,
    address: 'Camino a Sta. Teresa 1055, Heroes de Padierna',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    zipCode: '10700',
    latitude: 19.3121,
    longitude: -99.2156,
    phone: '55 5449 5500',
    emergencyPhone: '55 5449 5500',
    specialties: ['Urgencias', 'Cardiologia', 'Neurologia', 'Traumatologia', 'Oncologia', 'Cirugia Cardiovascular', 'UCI', 'Neonatologia'],
    hasEmergency: true,
    has24Hours: true,
    hasICU: true,
    hasTrauma: true,
  },
  {
    cluesCode: 'DFPRI00289',
    name: 'Hospital ABC Campus Santa Fe',
    type: InstitutionType.HOSPITAL_PRIVATE,
    attentionLevel: AttentionLevel.THIRD,
    address: 'Av. Carlos Graef Fernandez 154, Santa Fe',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    zipCode: '05300',
    latitude: 19.3591,
    longitude: -99.2621,
    phone: '55 1103 1600',
    emergencyPhone: '55 1103 1600 ext. 1111',
    specialties: ['Urgencias', 'Cardiologia', 'Neurologia', 'Oncologia', 'Trasplantes', 'Cirugia Robotica', 'UCI', 'Neonatologia'],
    hasEmergency: true,
    has24Hours: true,
    hasICU: true,
    hasTrauma: true,
  },
  {
    cluesCode: 'DFPRI00312',
    name: 'Hospital Medica Sur',
    type: InstitutionType.HOSPITAL_PRIVATE,
    attentionLevel: AttentionLevel.THIRD,
    address: 'Puente de Piedra 150, Tlalpan',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    zipCode: '14050',
    latitude: 19.3032,
    longitude: -99.1647,
    phone: '55 5424 7200',
    emergencyPhone: '55 5424 7200',
    specialties: ['Urgencias', 'Cardiologia', 'Neurologia', 'Oncologia', 'Trasplantes', 'Endocrinologia', 'UCI'],
    hasEmergency: true,
    has24Hours: true,
    hasICU: true,
    hasTrauma: true,
  },
  {
    cluesCode: 'DFPRI00345',
    name: 'Hospital Espanol',
    type: InstitutionType.HOSPITAL_PRIVATE,
    attentionLevel: AttentionLevel.THIRD,
    address: 'Av. Ejercito Nacional 613, Granada',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    zipCode: '11520',
    latitude: 19.4391,
    longitude: -99.1906,
    phone: '55 5255 9600',
    emergencyPhone: '55 5255 9600',
    specialties: ['Urgencias', 'Medicina Interna', 'Cardiologia', 'Traumatologia', 'Ginecologia', 'UCI'],
    hasEmergency: true,
    has24Hours: true,
    hasICU: true,
    hasTrauma: true,
  },
  {
    cluesCode: 'DFSSA000203',
    name: 'Hospital General Xoco',
    type: InstitutionType.HOSPITAL_PUBLIC,
    attentionLevel: AttentionLevel.SECOND,
    address: 'Av. Mexico Coyoacan 25, Xoco',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    zipCode: '03330',
    latitude: 19.3659,
    longitude: -99.1628,
    phone: '55 5601 3543',
    emergencyPhone: '55 5601 3543',
    specialties: ['Urgencias', 'Medicina Interna', 'Cirugia General', 'Ginecologia', 'Pediatria'],
    hasEmergency: true,
    has24Hours: true,
    hasICU: false,
    hasTrauma: false,
  },
  {
    cluesCode: 'DFSSA000245',
    name: 'Hospital General La Villa',
    type: InstitutionType.HOSPITAL_PUBLIC,
    attentionLevel: AttentionLevel.SECOND,
    address: 'Aquiles Serdan y Cantera s/n, La Villa',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    zipCode: '07050',
    latitude: 19.4856,
    longitude: -99.1189,
    phone: '55 5781 4300',
    emergencyPhone: '55 5781 4300',
    specialties: ['Urgencias', 'Medicina Interna', 'Ginecologia', 'Obstetricia', 'Pediatria'],
    hasEmergency: true,
    has24Hours: true,
    hasICU: false,
    hasTrauma: false,
  },
  {
    cluesCode: 'DFSSA000287',
    name: 'Hospital Pediatrico Coyoacan',
    type: InstitutionType.HOSPITAL_PUBLIC,
    attentionLevel: AttentionLevel.SECOND,
    address: 'Av. Copilco 302, Universidad',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    zipCode: '04360',
    latitude: 19.3335,
    longitude: -99.1778,
    phone: '55 5658 2322',
    emergencyPhone: '55 5658 2322',
    specialties: ['Urgencias Pediatricas', 'Pediatria', 'Neonatologia', 'Cirugia Pediatrica'],
    hasEmergency: true,
    has24Hours: true,
    hasICU: false,
    hasTrauma: false,
  },
  {
    cluesCode: 'DFSSA000350',
    name: 'Instituto Nacional de Cardiologia Ignacio Chavez',
    type: InstitutionType.HOSPITAL_PUBLIC,
    attentionLevel: AttentionLevel.THIRD,
    address: 'Juan Badiano 1, Seccion XVI',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    zipCode: '14080',
    latitude: 19.2923,
    longitude: -99.1569,
    phone: '55 5573 2911',
    emergencyPhone: '55 5573 2911',
    specialties: ['Cardiologia', 'Cirugia Cardiovascular', 'Electrofisiologia', 'Hemodinamia', 'UCI Cardiovascular'],
    hasEmergency: true,
    has24Hours: true,
    hasICU: true,
    hasTrauma: false,
  },
  {
    cluesCode: 'DFSSA000362',
    name: 'Instituto Nacional de Neurologia y Neurocirugia',
    type: InstitutionType.HOSPITAL_PUBLIC,
    attentionLevel: AttentionLevel.THIRD,
    address: 'Insurgentes Sur 3877, La Fama',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    zipCode: '14269',
    latitude: 19.2891,
    longitude: -99.1632,
    phone: '55 5606 3822',
    emergencyPhone: '55 5606 3822',
    specialties: ['Neurologia', 'Neurocirugia', 'Neurofisiologia', 'UCI Neurologica'],
    hasEmergency: true,
    has24Hours: true,
    hasICU: true,
    hasTrauma: false,
  },
  {
    cluesCode: 'DFAMB00001',
    name: 'Cruz Roja Mexicana - Delegacion CDMX',
    type: InstitutionType.AMBULANCE_SERVICE,
    attentionLevel: AttentionLevel.FIRST,
    address: 'Av. Ejercito Nacional 1032, Polanco',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    zipCode: '11510',
    latitude: 19.4352,
    longitude: -99.1979,
    phone: '55 5395 1111',
    emergencyPhone: '55 5395 1111',
    specialties: ['Urgencias', 'Atencion Prehospitalaria', 'Traslados'],
    hasEmergency: true,
    has24Hours: true,
    hasICU: false,
    hasTrauma: true,
  },
  {
    cluesCode: 'DFAMB00002',
    name: 'ERUM - Escuadron de Rescate y Urgencias Medicas',
    type: InstitutionType.AMBULANCE_SERVICE,
    attentionLevel: AttentionLevel.FIRST,
    address: 'Av. Insurgentes Sur 1915, Guadalupe Inn',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    zipCode: '01020',
    latitude: 19.3668,
    longitude: -99.1828,
    phone: '55 5588 5100',
    emergencyPhone: '55 5588 5100',
    specialties: ['Urgencias', 'Atencion Prehospitalaria', 'Rescate', 'Traslados'],
    hasEmergency: true,
    has24Hours: true,
    hasICU: false,
    hasTrauma: true,
  },
];

async function seedHospitals() {
  console.log('Iniciando seed de hospitales CDMX con especialidades...');

  for (const hospital of hospitalesCDMX) {
    await prisma.medicalInstitution.upsert({
      where: { cluesCode: hospital.cluesCode },
      create: {
        ...hospital,
        isActive: true,
        isVerified: true,
        verifiedAt: new Date(),
      },
      update: {
        name: hospital.name,
        type: hospital.type,
        attentionLevel: hospital.attentionLevel,
        address: hospital.address,
        city: hospital.city,
        state: hospital.state,
        zipCode: hospital.zipCode,
        latitude: hospital.latitude,
        longitude: hospital.longitude,
        phone: hospital.phone,
        emergencyPhone: hospital.emergencyPhone,
        specialties: hospital.specialties,
        hasEmergency: hospital.hasEmergency,
        has24Hours: hospital.has24Hours,
        hasICU: hospital.hasICU,
        hasTrauma: hospital.hasTrauma,
      },
    });

    console.log(`  ✓ ${hospital.name}`);
  }

  console.log(`\n✅ Seed completado: ${hospitalesCDMX.length} hospitales con especialidades`);
}

seedHospitals()
  .catch((e) => {
    console.error('Error en seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
